### ISSUE TITLE
Error on during import of AudioClip

### ISSUE THREAD

**Issue by rogersachan** [superusercode/PokemonUnity#6]
**Did you search for similar issues before submitting this one?**
Yes
**Describe the issue you encountered:**
Error on the import of the following audio clips (FSBTool64.exe)
```
387.ogg
496.ogg
497.ogg
608.ogg
655.ogg
392.ogg
388.ogg
495.ogg
609.ogg
391.ogg
607.ogg
448.ogg
652.ogg
500.ogg
447.ogg
395.ogg
390.ogg
657.ogg
654.ogg
499.ogg
389.ogg
658.ogg
394.ogg
393.ogg
```
**Expected behavior:**
Successful import
- Platform (Win7, 8, 10? macOS? Linux distro? WebGL?):
Win10
- Branch commit SHA:
latest
- Steps to reproduce:
    1. Import project in Unity

- Screenshot if needed (error files can be attached):

- Any related issues:

**Comment by superusercode** [comment]
@IIcolour Is it okay if I upgrade the project to the latest version of unity3d ?

**Comment by rogersachan** [comment]
@superusercode I haven't seen any impact

**Comment by rogersachan** [comment]
5.5.2 fixes this
